domains:
  - stashd
secured: true
services:
  - postgres
workers:
  - vite
custom_workers:
  schedule:
    label: Task Scheduler
    command: php tempest schedule:run
    schedule: minutely
container:
  port: 8474
  containerfile: Dockerfile
  target: dev
